name: Test
on: pull_request

jobs:
  phpcs:
    name: PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: docker://rtcamp/action-phpcs-code-review:v2.0.0
        with:
          php-version: '7.4'
